apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: deepseek
  namespace: vllm
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 50Gi
  storageClassName: default
  volumeMode: Filesystem
