apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: deepseek
  namespace: monitoring
  labels:
    release: prometheus
spec:
  selector:
    matchLabels:
      app: deepseek
  endpoints:
    - port: http
      interval: 10s
      path: /metrics
